#ifndef CONSTANTS_H
#define CONSTANTS_H

/* EXIT CODES */
#define EXIT_ON_SUCCESS     0x0000
#define EXIT_PORT_IS_USE    0x0010
#define EXIT_INVALID_ARGS   0x0020

/* SERVER CONSTANTS */
#define DEFAULT_PORT 8080

#define APPLICATION_NAME "Simple Http Server"

#endif // CONSTANTS_H
